version: '3.8'

services:
  php:
    build:
      context: docker
      dockerfile: php/Dockerfile
    volumes:
      - .:/var/www
    ports:
      - ${APPLICATION_PORT:-9000}:9000
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - ${MYSQL_PORT:-3306}:3306

volumes:
  db_data:
